### EFA 4 factor ###

CFA <- '
F1 =~ NA*SMKCES + PACKYE + SMKDEP + ALCDEP + ALCFRQ + COCDEP + CANEV + SMKINI + SMKAGE
F2 =~ NA*CANDEP + COCDEP + OPIODEP + SMKAGE
F3 =~ NA*ALCDEP + ALCCON + ALCFRQ + ALCP 
F4 =~ NA*CANEV + CANFL + SMKINI

F1~~1*F1
F2~~1*F2
F3~~1*F3
F4~~1*F4

'

### Bifactor by trait ###

bif <- 'G =~ NA*SMKINI + SMKAGE + CANEV + SMKCES + PACKYE + ALCCON + ALCFRQ + ALCP + CANFL + SMKDEP + ALCDEP + CANDEP + COCDEP + OPIODEP

INI =~ NA*SMKINI + SMKAGE + CANEV + SMKCES
FRQ =~ NA*PACKYE + ALCCON + ALCFRQ + ALCP + CANFL
DEP =~ NA*SMKDEP + ALCDEP + CANDEP + COCDEP + OPIODEP

G ~~ 0*INI + 0*FRQ + 0*DEP

G~~1*G
INI~~1*INI
FRQ~~1*FRQ
DEP~~1*DEP
'

### Bifactor by trait dropping SMKCES ###

bif <- 'G =~ NA*SMKINI + SMKAGE + CANEV + PACKYE + ALCCON + ALCFRQ + ALCP + CANFL + SMKDEP + ALCDEP + CANDEP + COCDEP + OPIODEP

INI =~ NA*SMKINI + SMKAGE + CANEV
FRQ =~ NA*PACKYE + ALCCON + ALCFRQ + ALCP + CANFL
DEP =~ NA*SMKDEP + ALCDEP + CANDEP + COCDEP + OPIODEP

G ~~ 0*INI + 0*FRQ + 0*DEP

G~~1*G
INI~~1*INI
FRQ~~1*FRQ
DEP~~1*DEP
'

### Bifactor by substance ###

bif <- 'G =~ NA*PACKYE + SMKCES + SMKDEP + SMKAGE + SMKINI + ALCCON + ALCFRQ + ALCP + ALCDEP + CANEV + CANFL + CANDEP + COCDEP + OPIODEP

SMK =~ NA*PACKYE + SMKCES + SMKDEP + SMKAGE + SMKINI 
ALC =~ NA*ALCCON + ALCFRQ + ALCP + ALCDEP 
CAN =~ NA*CANEV + CANFL + CANDEP 
DRG =~ NA*COCDEP + OPIODEP

G ~~ 0*SMK + 0*ALC + 0*CAN + 0*DRG

G~~1*G
SMK~~1*SMK
ALC~~1*ALC
CAN~~1*CAN
DRG~~1*DRG

a>.001
OPIODEP~~a*OPIODEP

b>.001
CANEV~~b*CANEV

c>.001
SMKINI~~c*SMKINI
'

### Bifactor by substance dropping DRG indicators ###

bif <- 'G =~ NA*PACKYE + SMKCES + SMKDEP + SMKAGE + SMKINI + ALCCON + ALCFRQ + ALCP + ALCDEP + CANEV + CANFL + CANDEP

SMK =~ NA*PACKYE + SMKCES + SMKDEP + SMKAGE + SMKINI 
ALC =~ NA*ALCCON + ALCFRQ + ALCP + ALCDEP 
CAN =~ NA*CANEV + CANFL + CANDEP

G ~~ 0*SMK + 0*ALC + 0*CAN

G~~1*G
SMK~~1*SMK
ALC~~1*ALC
CAN~~1*CAN

b>.001
CANEV~~b*CANEV

c>.001
SMKINI~~c*SMKINI
'